[project]
authors = ["arcjax07 <arcjax@proton.me>"]
channels = ["pytorch", "conda-forge"]
description = "Image Geolocalization!"
name = "image-geolocation"
platforms = ["linux-64"] # If arm, then you should remove hf-transfer and add "linux-aarch64" to the platforms array
version = "0.1.0"

[tasks]
download_data = "bash get_auxiliary_data.sh"

[dependencies]
python = ">=3.11.6,<3.12"
numpy = ">=1.26.4,<2"
pandas = ">=2.2.3,<3"
geopandas = ">=0.14.4,<0.15"
tensorboard = ">=2.18.0,<3"
georasters = ">=0.5.29,<0.6"
scipy = ">=1.14.1,<2"
pandarallel = ">=1.6.5,<2"
datasets = ">=2.19.2,<3"
pygeos = ">=0.14,<0.15"
pip = ">=24.3.1,<25"
ruff = ">=0.8.2,<0.9"
pytorch = "==2.5.0"
torchvision = ">=0.20.0,<0.21"
torchinfo = ">=1.8.0,<2"

[pypi-options]
index-url = "https://pypi.org/simple"
find-links = [{url = 'https://storage.googleapis.com/libtpu-releases/index.html'}, {url = 'https://storage.googleapis.com/libtpu-wheels/index.html'}]

[pypi-dependencies]
accelerate = ">=1.2.0, <2"
transformers = ">=4.47.0, <5"
srtm-py = ">=0.3.7, <0.4"
latlon-utils = ">=0.0.7, <0.0.8"
country-converter = ">=1.3, <2"
kgcpy = ">=1.1.8, <2"
hf-transfer = ">=0.1.8, <0.2"
