[project]
authors = ["arcjax07 <arcjax@proton.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "image-geolocation"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
pytorch = ">=2.5.1,<2.6"
torchvision = ">=0.20.1,<0.21"
numpy = ">=2.1.3,<2.2"
pandas = ">=2.2.3,<2.3"
geopandas = ">=1.0.1,<1.1"
